### PR TITLE
Ko test

### LINKED ISSUE #20: Add `ko test`
Add support for unit tests (similar to go)

- Only include `*_test.ko` files during testing
- Add `ko test <pkg>` command
- Add `Assert` like function(s)

### PR DESCRIPTION
**Pull request by ewoutp**
fixes #20 

Added `ko test <pkg> ...` command that compiles the given packages and runs all test functions in it.
A test function is a function that:
- has no arguments
- has a name that starts with `Test`

### CODE REVIEW

**Comment by ewoutp** [comment]
No. I'm assuming them to panic on failure.

**Comment by ewoutp** [comment]
See the `Assert` function(s) in the testing package

**Comment by petar** [comment]
How would you communicate soft/non-terminal errors like t.Errorf? Also
existing tests return true or false, so they’d probably need updating.

**Comment by ewoutp** [comment]
We could pass an struct to every test function with varieties such as `Error(string?)` but I'm not sure we really need that.

Adjusting the existing tests is probably doable.

**Comment by ewoutp** [comment]
We need to remove the TestAll anyway.

**Pull request merged**
